spring:
  application:
    name: jwt-login

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=prj
    username: postgres
    password: postgres

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      format_sql: true
    show-sql: true
  data:
    redis:
      password: gosl111
      port: 6379

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# web security config
jwt:
  secret-key: aGFlbmktand0LWxvZ2luLXByai1qd3Qtc2VjcmV0LWtleQo=
  encrypt-key: aGFlbmktand0LWxvZ2luLXByai1qd3QtZW5jcnlwdC1rZXkK
  access:
    token-header-name: Authorization
    expire-milliseconds: 1800000
    #expire-milliseconds: 10000
  refresh:
    expire-milliseconds: 3600000
    token-header-name: Authorization-Refresh

server:
  port: 8090