spring:
  application:
    name: jwt-login

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=prj
    username: postgres
    password: postgres

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      format_sql: true
      show_sql: true

# web security config
jwt:
  secret-key: a4781999a38ec1b56744a96fa09e956a987ca1de8ca05bfae077883d01d301dd64ec6b90a0cff7ba2ddbf1603a56f70bc039e102f168b2921d8937e9ad53b5ba
  access:
    expire-second: 1800000
  refresh:
    expire-second: 3600000

server:
  port: 8090